name: Deploy Production Environment

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    deploy_to_ecr:
        runs-on: ubuntu-latest
        environment:
            name: Production
            deployment: false

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Verify AWS Login
              run: |
                  aws sts get-caller-identity

            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and Push Docker Image
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: ${{ vars.PROJECT_NAME }}-app-repo
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                  docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
