name: Deploy Production Environment

on:
    workflow_run:
        workflows: ['Terraform Apply']
        types: [completed]
        branches: [main]

permissions:
    id-token: write
    contents: read

jobs:
    build_and_push:
        runs-on: ubuntu-latest
        environment:
            name: Production
            deployment: false
        outputs:
            image_tag: ${{ steps.output.outputs.tag }}

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Verify AWS Login
              run: |
                  aws sts get-caller-identity

            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v7.1.0
              env:
                  REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  REPOSITORY: ${{ vars.PROJECT_NAME }}-app-repo
                  IMAGE_TAG: ${{ github.sha }}
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT_NAME }}-app-repo:latest
                      ${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT_NAME }}-app-repo:${{ github.sha }}

            - name: Output Image Tag
              id: output
              run: echo "tag=${{ steps.login-ecr.outputs.registry }}/${{ vars.PROJECT_NAME }}-app-repo:${{ github.sha }}" >> "$GITHUB_OUTPUT"

    redeploy_ecs:
        runs-on: ubuntu-latest
        environment:
            name: Production
            deployment: false
        needs: build_and_push

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Redeploy ECS Express Service
              uses: aws-actions/amazon-ecs-deploy-express-service@v1.2.0
              with:
                  service-name: ${{ vars.PROJECT_NAME }}
                  image: ${{ needs.build_and_push.outputs.image_tag }}
                  execution-role-arn: ${{ secrets.AWS_ECS_EXECUTION_ROLE_ARN }}
                  infrastructure-role-arn: ${{ secrets.AWS_ECS_INFRASTRUCTURE_ROLE_ARN }}

                  # Container configuration
                  container-port: ${{ vars.APP_PORT }}
                  environment-variables: |
                      [
                          {"name": "PORT", "value": "${{vars.APP_PORT}}"},
                          {"name": "HOST", "value": "${{vars.APP_HOST}}"},
                          {"name": "MONGO_URI", "value": "${{secrets.APP_MONGO_URI}}"},
                          {"name": "JWT_KEY", "value": "${{secrets.APP_JWT_KEY}}"}
                      ]

                  # Resources
                  cpu: '256'
                  memory: '512'

                  # Scaling
                  min-task-count: 1
                  max-task-count: 1
