name: Deploy Production Environment

on:
    workflow_dispatch:

permissions:
    id-token: write
jobs:
    deploy_to_ecr:
        runs-on: ubuntu-latest
        environment:
            name: Production
            deployment: false

        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}
            - name: Verify AWS Login
              run: |
                  aws sts get-caller-identity
