name: Terraform Plan

on:
    pull_request:
        branches: [main]

permissions:
    id-token: write
    contents: read

jobs:
    plan_infrastructure_changes:
        runs-on: ubuntu-latest
        environment:
            name: Production
            deployment: false
        defaults:
            run:
                working-directory: ./tf_aws/
        env:
            TF_VAR_aws_region: ${{ vars.AWS_REGION }}
            TF_VAR_project_name: ${{ vars.PROJECT_NAME }}

        steps:
            - name: HashiCorp - Setup Terraform
              uses: hashicorp/setup-terraform@v4.0.0

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ vars.AWS_REGION }}

            - name: Checkout
              uses: actions/checkout@v6.0.2

            - name: Initialise Terraform
              id: init
              run: terraform init -backend-config="bucket=${{ vars.BUCKET_TF_STATE }}" -backend-config="key=${{ vars.BUCKET_TF_KEY }}" -backend-config="region=${{ vars.AWS_REGION }}"

            - name: Terraform Format
              run: terraform fmt -check

            - name: Terraform Validate
              id: validate
              run: terraform validate

            - name: Terraform Plan
              id: plan
              run: terraform plan
              continue-on-error: true

            - name: Post Plan to PR
              uses: actions/github-script@v9
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const output = `#### Terraform Init: \`${{ steps.init.outcome }}\`
                      #### Terraform Validate: \`${{ steps.validate.outcome }}\`
                      #### Terraform Plan: \`${{ steps.plan.outcome }}\`

                      <details><summary>Show Plan Output</summary>

                      ```
                      ${{ steps.plan.outputs.stdout }}
                      ```

                      </details>

                      *Triggered by @${{ github.actor }}, commit: ${{ github.sha }}*`;

                      github.rest.issues.createComment({
                      issue_number: context.issue.number,
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      body: output
                      });

            - name: Fail on Plan Error
              if: steps.plan.outcome == 'failure'
              run: exit 1
